dim_customer:
    catalog_id:
      dev: ""
      qa: ""
    staging_table:
      schema: dim_customer_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
      schema: bc_dim_customer_schema
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - customer_key
    full_load_table: True
    partition_key: row_number
    num_partition: 2
    update_timestamp_col : last_updt_col
    audit_seq_id: audit_id

dim_store:
    skip: True
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      schema: dim_store_schema
      path:
        dev: ""
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      schema: bc_dim_store_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - store_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : last_updt_col

dim_product:
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      schema: dim_product_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      schema: bc_dim_product_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - product_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : last_updt_col
    audit_seq_id : audit_id

fact_sales:
    skip : true
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      schema: fact_sales_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      schema: bc_fact_sales_schema
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - sales_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : sales_key
