dim_customer:
    schema_id:
      dev: dim_customer_schema
      qa: dim_customer_schema
    catalog_id:
      dev: ""
      qa: ""
    staging_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - customer_key
    full_load_table: True
    partition_key: row_number
    num_partition: 2
    update_timestamp_col : last_updt_col
    audit_seq_id: audit_id

dim_store:
    skip: True
    schema_id:
      dev: dim_store_schema
      qa : dim_store_schema
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      path:
        dev: ""
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - store_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : last_updt_col

dim_product:
    schema_id:
      dev: dim_product_schema
      qa : dim_product_schema
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - product_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : last_updt_col
    audit_seq_id : audit_id

fact_sales:
    skip : true
    schema_id:
      dev: fact_sales_schema
      qa : fact_sales_schema
    catalog_id:
      dev: ""
      qa : ""
    staging_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/staging/src/
    business_current_table:
      path:
        dev: s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
        qa : s3a://cogesak-etl-target/cogesak/datasets/lake/prod/src/
    point_in_time: true
    point_in_time_table:
      path:
        dev: ""
        qa : ""
    primary_keys:
      - sales_key
    full_load_table: false
    partition_key: row_number
    num_partition: 1
    update_timestamp_col : sales_key
